env:
  global:
  - DATE=$(date +%Y-%m-%d)
  - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
  - PACKAGE_NAME=tns-core-modules
  - NODE_VERSION=6.9.4
language: node_js
node_js:
- '6'
before_script:
- npm install -g grunt-cli
- npm install
script:
- grunt default
- FULL_PACKAGE_VERSION=$(node build/version.js)
- (cd tns-platform-declarations && npm pack)
before_deploy:
- mv bin/dist/$PACKAGE_NAME-$FULL_PACKAGE_VERSION.tgz ../.deploymentpackage
- mv build ../
- cd ..
- rm -rf NativeScript
- tar -zxvf .deploymentpackage
- mv package $PACKAGE_NAME
- cd $PACKAGE_NAME
- rm ../.deploymentpackage
- mv ../build ./
- node ./build/travis-scripts/add-publishConfig.js next
deploy:
  provider: npm
  email: nativescript@telerik.com
  on:
    branch: master
    skip_cleanup: true
  api_key:
    secure: VJksODKcxXltNTU1Unv4V3qZMI5rrAupuxnCUpIBxks6azi6/FvcW6ctMOj5wPQ9cQKPa8SgaKF/ksyueTmcUt+RznBWbGJ3lxe+6MF0Uk7OI3M3Ga8Ke/21KcZ1oIysgZ0JGCmyR9iAIoSHK1KarIYfiYo9dGWOSuDkqJzLTjk=
