language: node_js
node_js:
    4.2.3
before_script:
    - npm install -g grunt-cli
    - npm install
    - (cd build/platform-declarations && npm install)
script:
    - grunt default
    - (cd build/platform-declarations && grunt)
