env:
  global:
    - DATE=$(date +%Y-%m-%d)
    - PACKAGE_VERSION=$DATE-$TRAVIS_BUILD_NUMBER
language: objective-c
osx_image: xcode7.3
install:
  - brew update
  - brew install android-sdk
  - echo y | android update sdk -t android-23,build-tools-23.0.3,extra-android-m2repository --no-ui --all
before_script:
  - export ANDROID_HOME=/usr/local/opt/android-sdk
script: ./build.sh $PACKAGE_VERSION
before_deploy:
  - cd ./dist/package/
  - node ../../.travis/add-publishConfig.js rc
deploy:
  skip_cleanup: true
  provider: npm
  email: nativescript@telerik.com
  on:
    branch: master
  api_key:
    secure: J88MqLAoZStZZ77AAf+wgaoZp+8zG3fOUHRneSe4x/yEzyUShS9SlGuq0TSkm9sJVX94iHJl1BQ4yjLshOPV9dkOg1+BB4PbsDTKPCAhPCZgpW7WKz6iImmuWHArchLIRtI1fp+UYi1+V6c7gLALQPY7qR2QJcDJdq1tdgORAyGySMis95ttVhnn6DWTBbs/ocu+IzgOyBSkIiZR0mGk7q/pmVQPy+XL5PQoyUOhD4MmvAAIeVr+XoZ5I8pAUwhi1/bZijXrzWe7LbXh8pTDlEWvYduzYYjJZqUrHiE/e1e8/DIPXGaBUQBj7LRxSqqO8AJXGeCg4DF1R9j4CSG5c0pAwQ/U6vOGu8duPEGaoKG5+HlrTav7gI/YbwFA5HKyh1uzQ5trZDJ4mMKUoB1+8/eL2cjLudtyBB2Kg28wH6f78A9mQC1EJcP7Jz3qJTSUyhczIvwSF8/EkD8xmeaoTi2e+4TNgf7pys1cp6c7m7zKZbvVy25lfyAfG1rCF5+rzKj+GnE9mtLaY6VvlKWjyxklh8hfRBC94TZ8K7PH0tmdgk2Jal+OCdm9FDdmNrBSC1G/gPS8PchtffIRprPhNAUfcVpdg0rlQ4dckbGRbB5UBgwHkpoKasaSTx/nO85AiK6USIYOIod19loXUBvN3QyHUX76w265UhmTnb8iojo=
