name: 'apps/automated'

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1

      - name: Install NativeScript
        run: |
          python -m pip install --upgrade pip six
          npm i -g nativescript --ignore-scripts
          ns usage-reporting disable
          ns error-reporting disable
          ns doctor

      - name: Setup
        run: npm run setup
        
      - name: Download & install the Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.3

      - name: Set up platform tools like adb
        run: sdkmanager platform-tools

      - name: Start ADB and verify that pathing is working correctly
        run: adb devices

      - name: Verify $ANDROID_HOME is properly set for later Gradle commands.
        run: echo $ANDROID_HOME
        
      - name: Start Emulator  
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: node tools/scripts/run-automated.js android
        
      - name: Start iOS Simulator
        if: always() # run iOS tests even if Android tests failed
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 13 Pro'
          os_version: '>=15.0'

      - name: Test (iOS)
        if: always() # run iOS tests even if Android tests failed
        run: node tools/scripts/run-automated.js ios
